export default [
    {
      client: "Danny Gibson",
      occupation: "Personal Trainer",
      goal: "Danny wanted to defeat his procrastination and impostor sindrome so he could create an entire calisthenics online program within 2 months",
      how: "Danny was having some trouble creating the right environment to work in as well as getting himself motivated to ACTUALLY do it. What turned out to be the underlying problem? Impostor syndrome, which is always based on fear and insecurity. Once we tackled the real issue, it was much easier for Danny to feel motivated to do what he needed to get done. It was all about setting his eyes on the prize and always thinking about what mattered most: to achieve his goals so he could provide a better life for his son! Fortunately, once we dealt with all of this, Danny was able to push through and finish his Calisthenics program before the deadline!",
      testimonial: "Over exceeded what I asked for. Dez helped me finish a project I’ve been working on that needed to get done. His calls helped me gain clarity on what I needed to do, help me focus on the actions that mattered, and he also provided so deep questioning and motivation along my journey. Don’t hesitate but I hire him if you are stuck in a rut and need some momentum",
    },
    {
      client: "Giovanni Facchetti",
      occupation: "CEO & Founder",
      goal: "To be more aware of his actions on a daily basis. How he impacted others, how much time and attention he gave his family and friends, how he dealt with stress, etc.",
      how: "Giovanni has a very successful business. And ironically, that was the origin of most of his challenges! It was so successful that he couldn’t make time for the people who were most important to him. I had many sessions with Giovanni. He was always a gentleman. Always on time, always polite and always considerate of my time. As such, he always respected what I had to say and followed up on it. Our sessions were always constructive and in the end, Giovanni adopted new behavioral patterns that he could be proud of. Nowadays he is much more attentive to his family and he is much more practical when it comes to being goal-oriented.",
      testimonial: "I have been working with Dez on my accountability project. I can only wholeheartedly recommend him! He is indeed a very special person, with whom one quickly develops a relationship of trust. Always proactive, always centered, and extremely kind, he is a great support and a key component of the project's success. I look forward to continuing our work together.",
    },
    {
      client: "Keoni Tamayo ",
      occupation: "YouTuber",
      goal: "To create structure and systems to make it easier for Keoni to be consistent with his YouTube uploads and live sessions.",
      how: "Keoni was already in a great place, as he had been able to garner over 100k subscribers on his workout YouTube channel. However, he had run into a rut. He always procrastinated which ended up killing his QUALITY free time. All he needed was to learn to properly plan and execute. After that, we just had to tackle his self-discipline. Once I helped him plan, he saw that if he committed to what he needed to do, he would actually have PLENTY of free time to use. This reframing also helped him to become more self-disciplined. All this really motivated him to get stuff done instead of procrastinating and nowadays he seems like a new person. All thanks to some structure and proper planning!",
      testimonial: "Dez has really helped me out in terms of productivity and motivation. He's a great person to work with and really addresses the heart of the challenges you're facing. Thanks to him, I was able to put all my to-dos on my calendar and my follow-through has greatly improved. 5/5!",
    },
    {
      client: "Arno Schreuders",
      occupation: "Business Owner",
      goal: "Arno was happy with how his business was doing, but not happy with his own behavior and health. He wanted to defeat unhealthy habits and urges.",
      how: "Although he was financially successful, this client had a really hard time staying disciplined at home. He would indulge in unhealthy habits on a daily basis and wanted to start minding his health more, as he was nearing the age of 50 and had started to feel concerned about his life’s longevity. He wanted to stay around to watch his kids grow up! At first, it was a challenge to get Arno to properly track his daily activity, but once that became a solid habit everything became easier! Nowadays, Arno has a much more structured and well-planned life. He only has one cheat day and he is better able to control his urges.",
      testimonial: "Dez is a great coach and a great addition to all parts of my life! Thanks!",
    },
    {
      client: "Saleh Alkahtani",
      occupation: "Software Engineering Student",
      goal: "This client was looking for structure in his life. He also wanted to become more confident and feel like “more of a man”.",
      how: "Saleh was a lost University student. We worked on A LOT of different things and, ultimately, Saleh became a better man for it. He was much, much more disciplined by the end of the sessions. He was more confident, he believed in himself more and, more importantly, he stopped limiting himself so much. In my opinion, his self-limitations were the biggest deterrent to his goals. Although he never became as self-disciplined as I wish he could’ve become, he still ended up in a much better place than he first was when he came by. Unfortunately, because he is a student, he couldn’t continue to have more sessions due to financial reasons. But I hope my guidance can continue you to help him on his path!",
      testimonial: "Dez is an excellent coach, good listener, gives you great feedback and clear direct feedback and guidance to reach your goals. He has helped me get out of a rut and increase my productivity to a way higher level  than I was at before I hired him, I highly recommend him.",
    },
    {
      client: "Gun Clawvuthinan",
      occupation: "Crypto Expert",
      goal: "To become extremely disciplined. To be able to produce a certain amount of content every single week for his social media accounts.",
      how: "Gun had amazing ambitions since day 1. They were related to his personal fortune as well as social media success. To achieve it, he needed up improve his self-discipline a lot. Not only that, he needed to upgrade his organizational and structuring skills. We did just that. And currently, our sessions are more strategy-based where we focus on figuring out what the best next step is. Of course, sometimes we discuss matters related to mindset and personal issues, but we mostly focus on his professional endeavors",
      testimonial: "Great coach. He helped me to think for myself and asks good questions to let me really think about the exact situations in my life. He makes sure I am accountable for all my work + helps me to talk to myself out loud. Highly recommend Dez!",
    },
    {
      client: "Maxim Rempel",
      occupation: "eCommerce Owner",
      goal: "To defeat a serious case of procrastination and vulnerability of being easily distracted by friends. Essentially, to gain the habits and lifestyle of a successful entrepreneur.",
      how: "Maxim was someone who could really use a coach in his life. He had all of his goals well defined, he just wasn’t taking the path towards them. His biggest problem was the fact that nobody in his life had ambitions similar to his. They just wanted to have an easy job and enjoy their free time on the weekend while Maxim wanted to grow his own business and be financially independent. His friends would entice him to play video games every day. And I really do mean, entice him. They would almost stalk him until he would reply and then they would not take no for an answer and would almost force him to play with them. That was the biggest challenge we faced — getting Maxim to be able to say no and be assertive when he did so. After that was fixed, it was just a matter of coming up with the right habits and structure to become successful. After a few months, we were able to do so! And after a few more months, Maxim started to be super self-disciplined and doing everything he needed to do! I’m super proud of Maxim and it was a pleasure to work with him!",
      testimonial: "Dez is a great coach! In every meeting he made sure to discuss everything that was on my mind & brought always a solution to my problems. He gave advice on how to deal with my daily struggles & keep moving forward. If you need clarity, accountability & an extra of motivation, Dez is your man! Thanks for the value & pushing me beyond my limits!",
    },
    {
      client: "Muhsin Mohamed",
      occupation: "Prospecting Rapper",
      goal: "To become successful. To replace his non-productive habits with productive ones. We focused on fixing those habits and getting him success habits that he had to do every single day.",
      how: "With baby steps, eventually Muhsin managed to become one of my best-performing clients! He had many perfect weeks and became a self-discipline machine! At first, it was challenging since he had no quality habits AT ALL. But once he got the hang of it, he started to enjoy doing the habits. It became rewarding. After that, it was easy peasy!",
      testimonial: "So glad I came across this. It’s  so beneficial, Dez makes everything easy to understand and gets the best of you. I would do this over again no doubt, definitely recommend",
    },
    {
      client: "Gyuri Tóth",
      occupation: "eCommerce Expert",
      goal: "To become a better entrepreneur by improving his knowledge, setting up things faster, being more professional and structured, and having better consistent habits in his life.",
      how: "Gyuri was already on a good path. He just needed someone to hold him accountable and to ask him the right questions on a weekly basis. Our sessions were always very productive and always achieved some sort of goal! I can happily say that Gyuri is now an even better entrepreneur after this experience. His mindset also improved significantly.",
      testimonial: "Worked with Dez for a few months and it was a GREAT experience. He was always able to talk about all different areas that I needed and we both came up with a plan on how to achieve my goals. After that, it was just a matter of executing them. His accountability sheet did wonders for it. At first I didn't take it too seriously, but when I did I started seeing the results. If you're trying to be successful at any area of your life, Id definitely say Dez is the guy to help you do that",
    },
    {
      client: "Charles Thomas",
      occupation: "Entrepreneur",
      goal: "His goals, for now, are to become the best version he can be so that he’s better equipped to become an extremely successful entrepreneur. This means having success habits and being productive during the week towards the goal of creating multiple sources of revenue.",
      how: "When we first started working together, I told Charles what he was aiming for would take a while. Fortunately, he listened and was patient. After a couple of months, he was really able to hit his stride and by week 20 his performance seemed like that of a different person! It was a tremendous success. He is now much, much more self-disciplined and feels much more in tune with his journey and goals. He now makes the most out of every day and keeps on improving both his performance and the results of his efforts. There’s no stopping him now.",
      testimonial: "20 weeks later and I am transformed. This service is the best. This coach is very good at tightening up weak areas. I can't wait to see how much better I will be in another 20 weeks.",
    },
];
